### ISSUE TITLE
My sickrage freeze when i use the app

### ISSUE THREAD

**Issue by Noktam** [MGaetan89/ShowsRage#11]
Every time i use the app, nothing show up, but my sickrage freeze and needs to be restarted.
Sometime, after a while, i get the episode in the coming episode section, but that's it.
It's like it take few minutes to complete a request and that freeze the whole sickrage until it complete.

**Comment by MGaetan89** [comment]
Do you have this problem everywhere or only in some part? Any information can help me do figure out the issue.

**Comment by MGaetan89** [comment]
Closing as I don't have enough information to debug/fix this.
