### ISSUE TITLE
Playing video files

### ISSUE THREAD

**Issue by Quiksmage** [MGaetan89/ShowsRage#13]
Although I probably won't use the feature too often. Is this implemented yet? I can't find any option to play videos from inside shows seasons or episodes.

**Comment by MGaetan89** [comment]
Yes, it is implemented. But it may not work in every configuration.
You first need to activate the corresponding settings (one for Chromecast, one for streaming on your device). Then a Chromecast/play icon will be visible on the episode detail, if it was downloaded.

**Comment by Quiksmage** [comment]
Ah, I see. After enabling the settings I options to play it. I had thought experimental was similar to how plex has an experimental player apart from its normal player. Thanks for three quick response. I love the responsiveness of this app :)
