### ISSUE TITLE
BUG: Logs section

### ISSUE THREAD

**Issue by sharkykh** [MGaetan89/ShowsRage#132]
## Bug report

* ***ShowsRage* version:** 1.5
* **Android version:** 6.0.1
* **Device:** Samsung Galaxy S7

### Issue description
Connected using API, tested connection and show list - everything works fine.
Log section isn't working. SickRage logs show this error every time you refresh Logs on the app:
`[a3ce318] API :: coercing to Unicode: need string or buffer, NoneType found`

### Expected result
Log entries to show us.

### Steps to reproduce
I don't really know - I just downloaded the app and configured it using IP, Port then 'Get API'.

**Comment by miigotu** [comment]
Fixed
