### ISSUE TITLE
Option Season Folders not there

### ISSUE THREAD

**Issue by 03397** [MGaetan89/ShowsRage#140]
Thank you for contributing to *ShowsRage*. Please fill in the form corresponding to your request ("Bug report" or "Feature request"). The other sections can safely be removed.

## Bug report

* ***ShowsRage* version:**
* **Android version:**
* **Device:**

### Issue description
When I add a tv show there is no option to group episodes by season folder. This results to have all the episodes in a single folder.
Please advise.

Thanks
Nicolas

### Steps to reproduce

1.
2.
3.

**Comment by MGaetan89** [comment]
I will add this in the next version of the application.

**Comment by MGaetan89** [comment]
It will be part of version 1.7, which will be released soon.
