### ISSUE TITLE
Problem with Schedule display

### ISSUE THREAD

**Issue by gauth-fr** [MGaetan89/ShowsRage#146]
## Bug report

* ***ShowsRage* version: 1.6
* **Android version: 6.0 (EMUI 4.1)
* **Device: Huawei P9lite (2016)

### Issue description
Since last update, showing schedule doesn't work. ShowRage closes.
History widget is working fine but Schedule widget won't display anything

### Steps to reproduce

1. Start ShowRage
2. Display menu, click Schedule
3. App closes

1. Add Schedule widget on main screen
2. Click refresh
3. Nothing displayed

If there is anyway to retrieve logs let me know!

**Comment by MGaetan89** [comment]
This is already fixed.
I will release a new version in a couple of days
I'm waiting before the release in case other issues are reported.
