### ISSUE TITLE
Update Fdroid Version

### ISSUE THREAD

**Issue by isignupovertor** [MGaetan89/ShowsRage#150]
* ***ShowsRage* version: 1.1**
* **Android version: 8.1**

### Issue description

Currently version on Fdroid is 1.1. But github version 1.6? 

### Expected result

Fdroid has 1.6

**Comment by MGaetan89** [comment]
I'm not the one maintaining the Fdroid version.
I think it was the guys from Fdroid, so maybe you can check with them directly.
