### ISSUE TITLE
When adding a show you cannot select the 'root folder' from dropdown

### ISSUE THREAD

**Issue by binhex** [MGaetan89/ShowsRage#154]
Thank you for contributing to *ShowsRage*. Please fill in the form corresponding to your request ("Bug report" or "Feature request"). The other sections can safely be removed.

## Bug report

* ***ShowsRage* version:** 1.7 beta
* **Android version:** 7.1
* **Device:** Samsung Galaxy S7 Edge

### Issue description
When adding a new show you see a list of options, one of these options is to select the 'root folder' from what looks like it should be a dropdown (downwards arrow), but no options appear, even though i have multiple root folders defined.

Note:- I am using Medusa 0.2.5

### Expected result
I can select from the dropdown list of 'root folders'.

### Steps to reproduce

1. Install showsrage 1.7 beta
2. click on the + to add show
3. attempt to select a root folder and notice you can't.

## Feature request
N/A
### Description
N/A

**Comment by MGaetan89** [comment]
I can reproduce this one too.
I'll fix it and include it in the next beta too.
Thanks :)
