### ISSUE TITLE
ShowsRage crashes when viewing existing show

### ISSUE THREAD

**Issue by binhex** [MGaetan89/ShowsRage#155]
Thank you for contributing to *ShowsRage*. Please fill in the form corresponding to your request ("Bug report" or "Feature request"). The other sections can safely be removed.

## Bug report

* ***ShowsRage* version:** 1.7 beta
* **Android version:** 7.1
* **Device:** Samsung Galaxy S7 Edge

### Issue description
This looks to be a new bug introduced with the latest (current) beta. If i select an existing show from the list by clicking on it from the 'shows' screen i see the details of the show, however ShowsRage then crashes after around 2 - 3 seconds of this. I have tried viewing multiple shows and all of them behave in the same manner, so it doesnt look related to a single show.

Note:- Running Medusa 0.2.5

I have sent the crash report to you with a similar description name to this issue.

### Expected result
I should be able to click on a show and see the details of the show (series, imdb links etc) without ShowsRage crashing.

### Steps to reproduce

1. install Showsrage 1.7 beta
2. click on an existing show from the list of shows in the 'shows' screen
3. ShowsRage will then crash.

## Feature request
N/A
### Description
N/A

**Comment by MGaetan89** [comment]
Thanks for reporting this.
I am able to reproduce it. I will fix it and submit a new beta this week-end or next week.

**Comment by MGaetan89** [comment]
I just pushed a new beta, which fixes the two issues you reported.
Let me know if everything is working as expected.

**Comment by binhex** [comment]
Thanks I was just about to post to tell you both issues are confirmed fixed, awesome work!

**Comment by MGaetan89** [comment]
Thanks for the confirmation.
If nothing else comes up, I will release it for everyone in a few days.
