### ISSUE TITLE
Disable new version check

### ISSUE THREAD

**Issue by MGaetan89** [MGaetan89/ShowsRage#16]

**Comment by benyjr** [comment]
I vote for this.  I already have SickRage set to autoupdate.

I don't want to see an update notification everytime I open ShowsRage.

**Comment by MGaetan89** [comment]
Yes, I understand the need for this feature.
I don't know if I'll manage to include it the next version, but it will definitely make it in the following one in the worst case.

**Comment by benyjr** [comment]
Cool. As long as it's in the pipeline. 

I can be patient.

**Comment by MGaetan89** [comment]
I just implemented this.
It will be available in version 1.3 (version 1.2 is being deployed to test users and will be available in a couple of days).
