### ISSUE TITLE
Cache network response

### ISSUE THREAD

**Issue by didyouexpectthat** [MGaetan89/ShowsRage#18]
It takes over a minute to load my "Shows" page - normally my screen timeout is 15 seconds. As such, I have to continuously keep my screen open and active to ensure that the shows'll load eventually. If we could set a cache on the data that gets pulled, and then update asynchronously, I believe it would help load times for large libraries. 

![2015-09-29 03 58 28](https://cloud.githubusercontent.com/assets/1329077/10155004/bed9b910-6623-11e5-9c8a-04a3003898e7.png)

**Comment by duramato** [comment]
Yeah this needs to happen ,as someone with ~200 shows and a kinda poor server it takes a bit to load all especially if I'm not in my local network...

**Comment by MGaetan89** [comment]
I am woking on a solution for this in the next release.
But just out of curiosity:
- Can you tell me how many shows you have? You can see that at the bottom of each page in SickRage
- How long SickRage takes to returns that list? You can use the API builder and run the `shows` command to find that out (the API builder can be accessed on `/apibuilder` instead of `/home` on your SickRage web interface)

**Comment by duramato** [comment]
I have 220 shows , it takes 1192ms if im on my local network and 3461ms if im on another one

**Comment by didyouexpectthat** [comment]
I have 1315 shows. 
Remote: Response: 5079ms
Locally: Response: 5416ms

[edit] I updated them both to be more on-par. Something must have started when I went to grab the local option.

**Comment by MGaetan89** [comment]
Thanks for the feedback.
This will only let you access your shows faster by storing the data on your device. But it does not mean that the refresh will be faster.

**Comment by MGaetan89** [comment]
A small follow up on the progress of this task.
I am trying to save locally as many information as possible. So the application will feel more responsive, and will be usable while offline or outside of your local network (if you did not enable external access).
For the moment, the following parts are saved:
- The "History" section
- The "Logs" section
- The detail about the episodes

I am now working on the schedule section, and then the list of shows. When that's done, I will release the third beta of ShowsRage 1.4, and then the public release.

**Comment by MGaetan89** [comment]
I mostly need to do some polishing and testing now, and then I will release the third beta of ShowsRage. Expect it in the next two weeks.
The final public release will quickly follow, if no issues are reported.

**Comment by MGaetan89** [comment]
I just released version 1.4-beta3 of _ShowsRage_, which include a local database to improve access to your shows.
Let me know what you think of it (you need to be part of the beta program to receive the update. If you're not, you can find the instructions to join in the readme file).
