### ISSUE TITLE
Episode information does not update

### ISSUE THREAD

**Issue by Pikoulol** [MGaetan89/ShowsRage#19]
Steps to reproduce : 
- Select a show in "Shows" menu
- Select "Season 1"
- Select one episode in the list
- Swipe between episode : No information update :(

Android 5.1.1
ShowsRage 1.0.1

**Comment by MGaetan89** [comment]
Thanks for reporting this. I will fix it in the next version.
In the meantime, going back and selecting the desired episode works.

**Comment by MGaetan89** [comment]
I just released version 1.1, which fix this issue.
