### ISSUE TITLE
Search Option for filtering previously added shows

### ISSUE THREAD

**Issue by b2001l** [MGaetan89/ShowsRage#21]
It would be nice to have a search option on the Home screen to filter shows.
For example, currently in the show list. To find a show you must scroll through the list until you get to the show you are looking for. 

If there was an easily accessible search box, located at the top of the screen always, or in the menu to the side, it would increase the user ability to find a show they have already added quickly.

Thanks

**Comment by MGaetan89** [comment]
I am already planning to add the following two features in the next version:
- #2: Filter shows
- #3: Group shows/animes

Would those help you or is a search bar necessary?

**Comment by b2001l** [comment]
How will the "Filter Shows" option be implemented ?

If the filter shows includes an option to filter based on a text input this would be great. 

Also, it is a very amazing application. Appreciate the work involved in it. Thank you

**Comment by MGaetan89** [comment]
Thanks, I try to do my best to make it feature complete and easy to use :)

I didn't plan to include that yet. I don't know if it will make it in the next version, but I will include it.

**Comment by MGaetan89** [comment]
I just implemented this. It will be available in the next version (1.3).
