### ISSUE TITLE
Error When Adding a Show and Specifying quality 

### ISSUE THREAD

**Issue by benyjr** [MGaetan89/ShowsRage#26]
I was adding a show and discovered that if I special quality I get an error message as shown in the attached screen shot. 

Also when adding a new show, the default options saved in SickRage should be prepopulated. 

![screenshot_2015-10-10-17-35-52](https://cloud.githubusercontent.com/assets/14084052/10413428/245b8cea-6f76-11e5-8be1-a2b55586968a.png)
![screenshot_2015-10-10-17-35-42](https://cloud.githubusercontent.com/assets/14084052/10413431/2df3d7b2-6f76-11e5-8836-e56a6cacf120.png)

**Comment by MGaetan89** [comment]
I will have a look at the error. Should be easy to fix, so it will work in the next version.
For the default values, they are already used if you don't set them. But it is a good idea to display them in the form when adding a show.

**Comment by MGaetan89** [comment]
I fix the error. It will be available in the next version of ShowsRage.
The second point will have to wait until the next release.

**Comment by MGaetan89** [comment]
I created an other ticket for the second point: #32.
So I close this one as it is now fixed.
