### ISSUE TITLE
Add Locations For Adding Shows

### ISSUE THREAD

**Issue by ghost** [MGaetan89/ShowsRage#28]
Hi,

Could we add a location selector so people can pick what drive they want to save the new show to. 

Thanks

**Comment by MGaetan89** [comment]
I don't know if it is possible to select a specific folder, but I can add an option to select a specific root dir. Would that be enough?

**Comment by ghost** [comment]
Sure so if you can Select the Root Drive:

IE:\ Volume1\FOLDERNAME\NEW FOLDER ? or C:\FOLDERNAME\NEW FOLDER?

Something like this or see what you can do, Thanks

**Comment by MGaetan89** [comment]
The values I can show are the one you defined in SickRage > Config > General > Misc > Show root directories.

**Comment by MGaetan89** [comment]
I implemented your feature request in https://github.com/MGaetan89/ShowsRage/commit/37afb8dbbcdee2b714f715b496829abaf12b9333.
It will be available in the next version of _ShowsRage_ (1.4).

As said in my previous comment, the directories you can select are the one you defined in SickRage > Config > General > Misc > Show root directories.

**Comment by ghost** [comment]
Thanks

**Comment by MGaetan89** [comment]
If you use the beta version of _ShowsRage_, it is available in the version I released yesterday.
Otherwise, it will be available in a few weeks.
