### ISSUE TITLE
Bug on statistics

### ISSUE THREAD

**Issue by marco219** [MGaetan89/ShowsRage#31]
Total number of episodes is always 1 episodes smaller than the website. For instance i have 252 episodes and the app shows that i have only 251 episodes

**Comment by MGaetan89** [comment]
Those are data returned by SickRage.
I'll have to check there how to fix this.

**Comment by MGaetan89** [comment]
I am working on fixing this in SickRage. I'll let you know when it's done and released.

**Comment by marco219** [comment]
I think there is another problem that could be related to this one. The app statistics shows that I have one wanted episode, then when I check the episodes status management page on sickrage, I see no episodes checked as wanted. Hope this can help you

**Comment by MGaetan89** [comment]
The fix was merged in SickRage. It will be available in the next version.

**Comment by MGaetan89** [comment]
The fix was released today. Let me know if it works for you or if you still have some differences between the web part and the mobile part.

**Comment by marco219** [comment]
This is perfect ! Really good work you do

**Comment by MGaetan89** [comment]
Thanks for the feedback.
Glad you like it.
