### ISSUE TITLE
New Icon/Logo?

### ISSUE THREAD

**Issue by Concept211** [MGaetan89/ShowsRage#33]
Love the app and have been using it more frequently than the actual SickRage web UI. Thanks for the great work!

I wanted to offer if you wanted to use one of the logos I designed for SickRage. I can provide you with the hi-res PNG files with transparencies for you to use. Just let me know if you're interested. 

Here's a link to my post on the SR forums w/ the previews:
https://sickrage.tv/forums/forum/main-category/feedback-suggestions/29181-new-logo-suggestions-embedded

**Comment by MGaetan89** [comment]
Hi @Concept211 

Design is really not my strong suit, so any help on that level is always more than welcome. Even I don't like the current ShowsRage logos...

Both of your logos look great, with maybe a preference for the second one. The best for me is to have them in SVG format to include it in the application. Or I can give you a list of sizes the images should be in. Whichever is best for you.

If you want to know how it is used for the moment, you can look [here](https://github.com/MGaetan89/ShowsRage/tree/master/app/src/main/res) in the `drawable-*` and `mipmap-*` folders:
- `ic_notification.png`
- `ic_launcher.png`
- `ic_launcher_white.png`

I am trying to finish a new version for tomorrow, but it can be included in a future version.
I can credit you in the "About" section of the application and the release notes if you want.

Thanks for your contribution :)

**Comment by Concept211** [comment]
Awesome...not a problem. I'll get you the SVG hopefully today if I get a moment. I'll give you both versions so that you can try them and see which looks best.

Btw...I LOVE how you grab a dominant color sample from the show image/graphic and use it for that show's interface color scheme. Brilliant!

**Comment by Concept211** [comment]
Ok, here you go. I uploaded both SVG and hi-res PNG formats for both versions of the logo:
http://jmp.sh/ES7hrfQ

Let me know if they work out for you.

Thanks!

**Comment by MGaetan89** [comment]
Awesome, thanks!
I will try to integrate them this evening if I have time to show you what it looks like. Otherwise next week or in two weeks.

The dynamic design color is an idea taken from Material Design (the new Android design). I wouldn't have thought of that on my own :P

**Comment by Concept211** [comment]
Awesome...I can't wait to see it! I've been checking for updates within the app last night hoping it was updated but no such luck ;)

I've only seen the UI change colors like that within Google's Messenger app but those colors are completely random. I've never seen any app take a color sample from an image like that. Whoever's idea it is, it's slick!

**Comment by MGaetan89** [comment]
Here are previews of both logos in the application drawer of Android, compared to the current one:
![New logo 1](https://cloud.githubusercontent.com/assets/1009664/10617816/b8b6f264-776c-11e5-9392-cbbfd4daef4a.png)
![New logo 2](https://cloud.githubusercontent.com/assets/1009664/10617817/b8b93baa-776c-11e5-902d-9c443aef1573.png)

Now I see that the current logo is really blurry :o
The sharked-TV is still my favorite between the two of your icons. What do you think?

I also use the icon in white for the notification and in the sliding menu. Do you think you can make those icons in white too? Maybe just invert the colors (the white becomes blue and the blue becomes white).

I am trying to submit a new test version in the next hours. It won't include your icon, but I will include them before making the new version public :)

**Comment by Concept211** [comment]
Yeah, I think we can go with the shark/tv version. But the white line inside ended up coming out way too thin. I'll go ahead and revise it as well as give you the white version for the notification drawer. I'll have it to you shortly.

thanks!

**Comment by Concept211** [comment]
Here you go: http://jmp.sh/XgQ0wt3

I think it would look good if the default color scheme of the UI matched the colors of the new logo. I also included a banner image if you want to use it for the Google Play store page. Let me know if you need different sizes or whatever (I forget what the requirements are).

**Comment by MGaetan89** [comment]
That was a fast work ! Here are updated previews with the new logos.
It looks really cool. Great job :)

![screenshot_20151020-220824](https://cloud.githubusercontent.com/assets/1009664/10619846/2173d41a-7778-11e5-8e42-1b1c0da083c2.png)
![screenshot_20151020-220830](https://cloud.githubusercontent.com/assets/1009664/10619847/218d9cb0-7778-11e5-98f4-9e72a9616eda.png)

For the colors, I chose a set from [here](http://www.google.com/design/spec/style/color.html), to stay as close to Material Design guideline as possible. I don't mind using other colors. I just need to check the final result.
In the application, I use #3F51B5 and #303F9F as the main colors. All the colors I use are listed [here](https://github.com/MGaetan89/ShowsRage/blob/master/app/src/main/res/values/colors.xml).

For the Play Store, they ask for the banner of 1024x500. The banner you suggested is fine for me. So I guess you just have to move the text on the right of the logo to fit in the required dimension?

Sadly, I didn't have time to finish the new version today. So it will have to wait next week. At least it will include you new logo.

I really appreciate your contribution here. It really helps ShowsRage looks better! If you have a website/link or something that I can add in the app or here, let me know. And I will gladly promote your work if you want.

**Comment by Concept211** [comment]
Yeah I would use a sample of these values:
#13537F
#09769F
#038EB7

Here's the Google Play banner to spec: http://jmp.sh/6APheDB

Yeah, I'd appreciate the mention :+1:  I'm in the process of redesigning my website but you can link it www.concept211.com

Thanks again!  Looks great so far.

**Comment by MGaetan89** [comment]
I've been playing with the new colors and logo for the past week, and the result is really nice.
I used #09769F and #13537F for the colors.

Here are a couple of screenshots:

![Shows list](https://cloud.githubusercontent.com/assets/1009664/10771056/fbadea78-7cee-11e5-8c7d-aa5b2d78d987.png)
![Application drawer](https://cloud.githubusercontent.com/assets/1009664/10771057/fbb1da3e-7cee-11e5-92dd-b9e4800f371c.png)

**Comment by Concept211** [comment]
I love it...great job!  Can't wait to update ;)  No offense to the original product, but I feel these colors are easier on the eyes. I just feel the whole "Material" color scheme is a bit too harsh.  I love Google's push for simple/clean designs, but the colors are a little much ;)

**Comment by MGaetan89** [comment]
I just pushed the changes for the new logo and colors (https://github.com/MGaetan89/ShowsRage/commit/13414a793dbf8375f54e7cec01b0f160dde0a5b1). If you want to change something else, let me know and I will see what I can do.
I added a link to your website in the application and I will credit you in the release note of the next version (next week at the latest).
Thank you a lot for this contribution. It really helped the application look better :)

**Comment by Concept211** [comment]
I'm really happy to be a part of it! So is there a build/.apk anywhere to update manually without having to wait for Google Play to update?

**Comment by MGaetan89** [comment]
Not for the moment, no. I still have one thing I want to fix before the release.
Hopefully I will managed to do it today, so it will be available later this evening.
It will be available in the beta channel first. So you can subscribe to the beta version if haven't yet.

**Comment by MGaetan89** [comment]
Sadly, the release is still not for today.
I will have more time next week to finish and publish it.

**Comment by MGaetan89** [comment]
I will release the next version in a few minutes.
It will be available to the tester soon.

**Comment by Concept211** [comment]
Came out great! Thanks again!

**Comment by MGaetan89** [comment]
You did most of the work here ;)
