### ISSUE TITLE
Hard disk control

### ISSUE THREAD

**Issue by marco219** [MGaetan89/ShowsRage#34]
I noticed that when as soon as i open the app my hard drive is starting(because after some time of inacivity it goes idle). This is not happening when i use the website of sickrage. My question is does your app trigg some process?

**Comment by MGaetan89** [comment]
ShowsRage does not start any process. If your hard disk in starting when opening the application, I guess it is something done in SickRage, in the management of the API.

**Comment by marco219** [comment]
Ok i understand your point but every time i start the app my hard disk start spinning back and this is not happening with the webapp

**Comment by MGaetan89** [comment]
Did you try with an other Android application to see if the same thing happens?
I don't have access to your hard drive from the application, so I can not do anything about that.
You need to see that with SickRage's developers.

**Comment by marco219** [comment]
Ok thanks for you help. I will be in touch as soon as i do it

**Comment by marco219** [comment]
I tried the app Droidbeard this morning and my disk was idle and as soon as i use showrage the disk started.  But i dont know what is happening because there is nothing in the log that could explain it

**Comment by MGaetan89** [comment]
Did your hard disk start when you used Droidbeard? Or only with ShowsRage?

**Comment by marco219** [comment]
Only on showsrage. Maybe showrage trigg some index of the hard disk? Or
maybe it's the process that search for update?

**Comment by MGaetan89** [comment]
As I said, I don't have direct access to your hard drives from the app.
The only I can think of that may be related, is the request I make to get the list of root directories.
Maybe SickRage check if the root directories are valid before sending back the result, and that may cause the hard drive to start. But I am not sure. You have to check with SickRage developers.

**Comment by marco219** [comment]
Ok but what i have to ask them?

**Comment by MGaetan89** [comment]
It depends what you want to know.
Maybe what can cause your hard disk to start.
