### ISSUE TITLE
Logs autoupdate

### ISSUE THREAD

**Issue by duramato** [MGaetan89/ShowsRage#35]
Have something to autoupdatr the log page x number of sec
Also an option to filter certain log lines from showsrage page,like the api acess granted ,which is useful when trying to debug issues with SR self (having a remove log console ;) )

**Comment by MGaetan89** [comment]
There is a basic filter in the logs in the first beta of 1.6.
And I'm starting work on the auto-refresh now.

There will be a new setting for this. By default it will be disabled, but it will be possible to specify the refresh interval from a predefined list. I'm thinking about 30 seconds, 1 minute, 2 minutes and 5 minutes.
What do you think?

**Comment by duramato** [comment]
Sounds good, any reason for a present values? You could do something like Android's selection of time (like on the alarm clock app) that would allow for everyone's liking.

**Comment by MGaetan89** [comment]
I just followed what I did for the the version check option. I'll keep the same behaviour for this version, as I want to finish this version soon.
I'll have a look in v2 for a better implementation.

**Comment by MGaetan89** [comment]
This feature is being implemented in #130.
It will be part of the 1.6 release.

**Comment by MGaetan89** [comment]
This was merged in 1.6. It will be available in the next beta of ShowsRage.
