### ISSUE TITLE
Offline mánager of sickrage

### ISSUE THREAD

**Issue by AugustoWYZ** [MGaetan89/ShowsRage#46]
The ability of add shows or change status of caps/shows when you're not close to home network. When the server becomes un rage changes should be passed on

**Comment by MGaetan89** [comment]
I did not understand what you want. Can you try to explain it again?

**Comment by AugustoWYZ** [comment]
Sure, let's say I am at work and somebody tell me about this awsome show. I want to download but by the time I reach home I forgot what show is. If while they are telling me about the show I can add it to my showsrage and when my server is available then the showsrage adds it to sickrage automatically

**Comment by MGaetan89** [comment]
You can already add new shows from the app.
If your SickRage installation is accessible from outside of your home network, your can already do that.

**Comment by AugustoWYZ** [comment]
That's precisely the idea, the sickrage is not accessible, then we can use the app whenever we are and when the sickrage server becomes accessible for the app then the app makes the "offline" changes to the server

**Comment by MGaetan89** [comment]
You need to have access to your SickRage installation to perform the search. So it is not possible to include this.
