### ISSUE TITLE
Use Parcelable instead of Serializable

### ISSUE THREAD

**Issue by se-bastiaan** [MGaetan89/ShowsRage#47]
I noticed that all the models implement the Serializable interface. Since this is an Android application I would like to suggest switching to using the Parcelable interface, it's much faster and more efficient.

http://www.developerphil.com/parcelable-vs-serializable/
http://stackoverflow.com/questions/3611843/is-using-serializable-in-android-bad/3612364#3612364

**Comment by MGaetan89** [comment]
I have planned to do that (it's hidden somewhere on a todo list :p), but I was too lazy to do it until now.
I will try to make the switch in the next version or the following one.

**Comment by se-bastiaan** [comment]
:)

**Comment by MGaetan89** [comment]
I switch to `Parcelable` in 7ec8584: I removed all `implements Serializable` and implemented `Parcelable` where necessary.
