### ISSUE TITLE
Consistent refresh UI pattern

### ISSUE THREAD

**Issue by se-bastiaan** [MGaetan89/ShowsRage#48]
Currently the ShowsActivity uses a refresh button in the toolbar while the LogsActivity and HistoryActivity use the pull-to-refresh pattern. I think it would be good to make this more consistent by using one of these ways for the list refresh.

In the end consistency will make the app easier to use. Users will only need to learn the action once.

**Comment by MGaetan89** [comment]
This was fixed in #86 and will be available in the next version of ShowsRage (1.5).
