### ISSUE TITLE
Incorrect selection state in navigation drawer

### ISSUE THREAD

**Issue by se-bastiaan** [MGaetan89/ShowsRage#49]
Steps to reproduce:
1. Open the application
2. Make sure the 'shows' item in the navigation drawer is selected
3. Select one of the following items in the navigation drawer:
     - Statistics
     - Settings
     - Post Processing
     - Check for update
     - Restart
4. Close the dialog or activity shown by the previous chosen action.
5. Now that you're back in the previous activity the navigation drawer is still open, the item you selected in step 3 is still shown as being active but you're actually still in the ShowsActivity and thus 'Shows' should be active.

**Comment by MGaetan89** [comment]
I'm working on #50 at the moment, and this should be fixed at the same time.

**Comment by MGaetan89** [comment]
This is now fixed in the latest development version. It will be available in the next release.
Thanks for reporting it.
