### ISSUE TITLE
Is there any particular reason for using activities only?

### ISSUE THREAD

**Issue by se-bastiaan** [MGaetan89/ShowsRage#50]
I noticed that the main actions in the navigation drawer are all different activities that are being linked to. So every item opens a new activity when it's selected and finishes the previous one.

The animation that is presented during this action really shows that you're going to a totally different screen, but the navigation drawer is still present in the view that we're descending to. It's on the same level in the navigation hierarchy. Why not use fragments to handle this?

**Comment by MGaetan89** [comment]
There is no special reason for that.
At some point I intended to use only `Activity` or `Fragment`, but the application was getting more and more features and I never took the time to do that change. I am planning to do a performance/architecture oriented release that will change that.

**Comment by se-bastiaan** [comment]
Great. I noticed that you have the fragments to do this, they're just being used in different activities instead of one where they would replace each other. Thus the basis is in place.

**Comment by MGaetan89** [comment]
I want to remove the listeners implemented in the `Activity` with `Intent`s first. Then I can switch to single-`Activity` architecture.

**Comment by MGaetan89** [comment]
This will be available in the next version.
There might be a couple of changes left to do, so I keep the issue open until the release.

**Comment by MGaetan89** [comment]
One issue was introduced with this changed: when navigating back to a `Fragment` with a `ViewPager`, the previously selected tab is not saved, and the first one is selected.
For example, if you are on the detail of an episode and press back, you should arrive on the list of episodes of a specific season. Now it redirects to the detail of the show.
I will fix that in the next beta version.
