### ISSUE TITLE
Why include the navigation drawer in child activities?

### ISSUE THREAD

**Issue by se-bastiaan** [MGaetan89/ShowsRage#51]
The child activities in the application all contain the same navigation drawer that is given to the user in the main parent scene. According to the [material design guidelines](https://www.google.com/design/spec/patterns/navigation.html#navigation-patterns) the navigation drawer is only appropriate for parents with siblings and lateral navigation.

Opening a child activity (a specific show for example) is a descending navigation motion, a child of one of the parents in the sibling hierarchy (aka the items in the navigation drawer).

A great example where this goes wrong is the Settings screen, there I can return to the previous screen (which would be a logical approach) or I can open the navigation drawer and go to settings from settings in an endless loop.

**Comment by MGaetan89** [comment]
The Navigation Drawer is always available so you can quickly and easily navigate between the sections of the application.
If you look at the Play Store or Gmail, for example, you can always access the Navigation Drawer, even if you are in an application detail or reading an email.
I agree however that in those applications, the Navigation Drawer is not available in the settings. I am not sure if this is really an issue...

**Comment by se-bastiaan** [comment]
I actually didn't know that that was possible in the Play Store & Gmail. There is no visual clue that it would even be possible. But that Google does it doesn't mean that it is the way to go, at least that's what I've learned.

If you switch to fragments only then the problem with the settings will be resolved I guess.
