### ISSUE TITLE
Can't play shows in external player

### ISSUE THREAD

**Issue by Molleke** [MGaetan89/ShowsRage#52]
Everytime I want to use this option and I select my external player (tried Mx player Pro, ES Media Player and normal Samsung VideoPlayer) I get a message "Can't play this link". What can I do to make this work on my Samsung Galaxy Note 4?

**Comment by MGaetan89** [comment]
I tried with VLC and MX Player and it is working fine for me.
Are you trying to watch a video that is not in the default root directory?

**Comment by Molleke** [comment]
Root directory of my phone? I have my SickRage server running on my PC and not my phone. Also the tv shows are downloaded to my PC and not my phone. Through your android app I am connected to the Sickrage server on my PC and I can see all shows and then hit the play button for an episode in your app.

**Comment by se-bastiaan** [comment]
Root directory inside sickrage.

**Comment by Molleke** [comment]
What is the default root directory?

**Comment by MGaetan89** [comment]
The root directories is a setting in SickRage that allows you to store your shows in different directories. If you don't know what it is, then this is probably not the cause of your issue.
Is this feature broken for every shows or are you able to stream some of them?

**Comment by Molleke** [comment]
I have set the root directory in SickRage (see below). Didn't know that it was called that way.
![knipsel](https://cloud.githubusercontent.com/assets/12209079/11610035/7cbf36d2-9b97-11e5-8e61-94eaf987a675.PNG)

In the root directory are my tv shows with the downloaded episodes (see below for a few shows):
![knipsel](https://cloud.githubusercontent.com/assets/12209079/11610057/f93ce628-9b97-11e5-84d9-ff734d9d3da1.PNG)

I can't get a single one to play.

**Comment by MGaetan89** [comment]
Thanks for the information.
Maybe the issue comes from the fact that you have a space in your root directory name. I will investigate more on this and give you more information as soon as possible.

**Comment by MGaetan89** [comment]
Hi @Molleke.
I am looking into this issue, but I am not able to reproduce it.
Can you tell me if this is still broken for you in the latest version of ShowsRage (1.4.1)?

**Comment by Molleke** [comment]
Hi Gaëtan,

It is fixed in the latest version so it is no issue anymore.

Thnx.

2016-08-21 16:55 GMT+02:00 Gaëtan Muller notifications@github.com:

**Comment by MGaetan89** [comment]
Glad it is working.
Thank you for the confirmation.
