### ISSUE TITLE
Hide API logs when viewing debug logs

### ISSUE THREAD

**Issue by fernandog** [MGaetan89/ShowsRage#53]
the app only show api logs. Nothing else.
I would hide them so we can see other threads debug logs

**Comment by MGaetan89** [comment]
How should I filter that?
Check if the log starts with `TORNADO :: API ::`?

**Comment by fernandog** [comment]
I think its a good idea. Each refresh shows a lot of then. What do you think?

**Comment by fernandog** [comment]
I would also increase number of lines to show.

**Comment by MGaetan89** [comment]
I am already display everything SickRage returns, and it is not possible to ask for more.
What if people want to see the logs for the API (like in https://github.com/MGaetan89/ShowsRage/issues/35)?
I think it will be better to just add a search field so user can filter the logs.

**Comment by duramato** [comment]
@MGaetan89 @fernandog ideia its preety cool i found myself wanting to see sr logs like pp and the log where filled with the api ones

**Comment by fernandog** [comment]
Why not create a special filter for API?
Info. Debug. Warning. Api?

**Comment by fernandog** [comment]
Lets say you ask 20 lines When you do, SR adds 10 more log lines (api). So debug without api would be 10 lines only. If you have too many shows you will only see API logs

**Comment by MGaetan89** [comment]
I agree that API could be in a separate category. But this has to be done on SickRage side. There is already a category for database logs if I am not mistaken. It might need to be discussed, as other applications won't receive API logs anymore if we change that.
We could also update the API to allow request more items in the logs.

**Comment by fernandog** [comment]
Why not filter in ShowsRage?

**Comment by MGaetan89** [comment]
Because if all the logs I receive in ShowsRage in debug are about API, removing those items won't solve your issue. I can't request more logs than what I currently receive.

**Comment by MGaetan89** [comment]
In #67, I am implementing a filter for the logs. You will then be able to hide all API related calls.
But my previous comment about receiving only API related logs is still valid.

**Comment by MGaetan89** [comment]
#68 was just merged. It allows you to select which "section" of the logs you want to display. Those sections are based on the values received from SickRage.

![Filter logs](https://cloud.githubusercontent.com/assets/1009664/16902517/35ff920c-4c61-11e6-8827-198256fe4857.png)
