### ISSUE TITLE
Failed doing web ui callback

### ISSUE THREAD

**Issue by marco219** [MGaetan89/ShowsRage#56]
Since last SickRage update I can't add show in the ShowsRage, banner are not showing, the logs on the app are not available (I get N/A on each line). SickRage keep crashing every time and I got error each time I use the app.
Here are the logs from the web site

```
2016-01-07 09:19:15 ERROR::TORNADO::API :: __init__() takes exactly 3 arguments (2 given)
2016-01-07 09:19:15 ERROR::Thread-259::Failed doing webui callback: Traceback (most recent call last):

2016-01-07 09:19:15 DEBUG::Thread-259::API :: show.getbanner: curKwargs {'tvdbid': '259765'}
2016-01-07 09:19:12 ERROR::TORNADO::API :: __init__() takes exactly 3 arguments (2 given)
2016-01-07 09:19:12 ERROR::Thread-257::Failed doing webui callback: Traceback (most recent call last):

2016-01-07 09:19:12 DEBUG::Thread-257::API :: show.getbanner: curKwargs {'tvdbid': '259765'}
2016-01-07 09:19:12 ERROR::TORNADO::API :: __init__() takes exactly 3 arguments (2 given)
2016-01-07 09:19:12 ERROR::Thread-256::Failed doing webui callback: Traceback (most recent call last):

2016-01-07 09:19:12 DEBUG::Thread-256::API :: show.getbanner: curKwargs {'tvdbid': '289079'}
```

**Comment by MGaetan89** [comment]
Which fork of SickRage are you using? The old one or the new one?

**Comment by marco219** [comment]
I dont know. I'm using the master branch.
This one :
BRANCH: (master) / COMMIT: (9226ba5efba06fb9defc5272f03dae5d6d1c4145)

**Comment by MGaetan89** [comment]
You can find this information by going to the `/config/` page of your SickRage, at the bottom of the page (a link to "Website" or "Source").
From the line you posted, I guess you are using the original SickRage. I haven't used it for a few weeks now, so I will have to check what they changed to see why you have this issue.

From the content of the logs you posted, I guess they changed something in SickRage that broke the API. It may be an issue to report on the SickRage project directly.

**Comment by marco219** [comment]
Could you give me the new sickrage github link. Currently i'm using this one
https://github.com/SiCKRAGETV/SiCKRAGE/
But they've not pushed a commit in a whilr

**Comment by marco219** [comment]
Should i use this git repo of sickrage ?
https://github.com/SickRage/SickRage

**Comment by MGaetan89** [comment]
Yes, this is the new repository. They explain here how to switch the repository: https://github.com/SickRage/sickrage-issues/issues/3
Make sure you backup your SickRage installation first, in case something goes wrong!

I noticed that there were a lot of changes on the API side in https://github.com/SiCKRAGETV/SiCKRAGE/ in the last few weeks, so it is possible that they change/broke something. If you don't want to change the repository, you can see with them if they know something about this issue.

**Comment by MGaetan89** [comment]
Did you manage to fix this or switch repo?

**Comment by marco219** [comment]
No i didn't try to fix it but i'm gonna switch to the new git. Actually i'm
trying sonarr which is really great

**Comment by MGaetan89** [comment]
I had a look at sonarr once, but never tried it. I agree that it looks nice.
I noticed that a new version was just released for your fork of SickRage. Maybe it fixes your issue.

**Comment by MGaetan89** [comment]
Do you still have issue to connect to SickRage of can I close this?

**Comment by marco219** [comment]
Yes you can as I'm not using sickrage anymore I don't know if the problem
exist
