### ISSUE TITLE
Sort by Title

### ISSUE THREAD

**Issue by seanmccabe** [MGaetan89/ShowsRage#59]
Be great to be able to sort the titles to ignore 'The' 

ie "Flash (2014)"  instead of "The Flash (2014)"

**Comment by MGaetan89** [comment]
An improvement in the sort is planned in a future version. Maybe in version 1.5.

**Comment by MGaetan89** [comment]
I integrated this request in _ShowsRage_.
It will be available in the next version (1.5).
