### ISSUE TITLE
Language choice

### ISSUE THREAD

**Issue by froggy974** [MGaetan89/ShowsRage#61]
- **_ShowsRage_ version:** 
  1.3
- **Android version:**
  5.1.1
- **Device:**
  Nexus 4
## Feature request

Language choice
### Description

Can you consider adding an option in order to change apps language to English instead of default android language ?

**Comment by MGaetan89** [comment]
ShowsRage is only available is French and English, and default to English if your phone is in an other language.
Why would you need this setting? Are some parts of the application wrongly translated? Or mixed languages?

**Comment by froggy974** [comment]
My phone is in French, but I prefer to have the app in English.
I use sickrage in English, and I am a bit confused with the terminology differences.
For example Snatched vs récupéré

**Comment by MGaetan89** [comment]
I see. I will consider this for a future release. But it is not the top priority for the moment.

**Comment by froggy974** [comment]
Merci ,
C'est déjà super sympa de mettre cette app à disposition .

**Comment by MGaetan89** [comment]
Je laisse cette issue ouverte jusqu'à ce que ce soit intégré ;)

**Comment by MGaetan89** [comment]
Je viens d'intégrer cette fonctionnalité.
Elle sera disponible dans la prochaine version de _ShowsRage_ (1.5).
