### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by duramato** [MGaetan89/ShowsRage#66]
## Feature request

A  Widget for ShowsRage
### Description

Have a widget to be able to see the Schedule, with the shows airing today and soon.

**Comment by MGaetan89** [comment]
I was thinking about that a couple of weeks ago.
I might also add a widget to display the history.

**Comment by MGaetan89** [comment]
Moving this to 1.6, so I can release an intermediate release with some other new features and bug fixes.

**Comment by MGaetan89** [comment]
The history widget was merged for the 1.6 release.
The schedule widget and quick show access widget will soon follow.

**Comment by MGaetan89** [comment]
The quick show access widget was merged in the 1.6 release.
Next and final one will be the schedule widget.

**Comment by MGaetan89** [comment]
The schedule widget was merged in the 1.6 release.
It is the same as the history widget, except, of course, for its content.
I will publish a new beta soon with this new widget in it.

[Schedule widget](https://github.com/MGaetan89/ShowsRage/blob/2a0e041d0a3bbdc72feb50e667155cfc020b94c3/app/src/main/res/drawable-en-nodpi/widget_schedule_preview.png)
