### ISSUE TITLE
Shows Window Flickering and menu navigation issue

### ISSUE THREAD

**Issue by georgethemarmot** [MGaetan89/ShowsRage#71]
## Bug report

Replicated on ShowsRage 1.4 and 1.4.1
Tested after data purge
Android 6.0.1 Stock without root
Nexus 5
### Issue description
- Shows page flickering on opening
- Back button from Settings page sends the application into background.

https://www.dropbox.com/s/f8ffmh0ey62vn42/2016-06-06_23-12-05_showsrage.mp4

**Comment by MGaetan89** [comment]
Those issues are now fixed and will be part of the next version of ShowsRage (it should be available in the next two weeks).
