### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ghost** [MGaetan89/ShowsRage#8]
Hi,

It keeps on telling me cannot get API even though i have the IP, Port and username and password correct?

Is this only for external or Internal as well ?

Thanks

**Comment by MGaetan89** [comment]
What did you set for the path?  Just `api` or do you have subfolders?
ShowsRage should work for internal and external network, as long as you have access to it.

**Comment by ghost** [comment]
I have it installed on my Synology NAS and i access it via HTTPS://IP:PORT am i being dumb here or is there something else i need to know.

**Comment by MGaetan89** [comment]
There is an issue preventing the app from working when using HTTPS (see #7).
I will fix it and release a new version soon.

**Comment by MGaetan89** [comment]
I just fixed the issue. It will be available in the next version (1.0.1) in a few hours.
Let me know if it is working properly for you know.

**Comment by ghost** [comment]
It is working thanks alot :)
