### ISSUE TITLE
Asks to overwrite when setting episode status

### ISSUE THREAD

**Issue by DragonCannon** [MGaetan89/ShowsRage#89]
Thank you for contributing to _ShowsRage_. Please fill in the form corresponding to your request ("Bug report" or "Feature request"). The other sections can safely be removed.
## Bug report
- **_ShowsRage_ version:** 1.4.1
- **Android version:** 5.1, 6.0
- **Device:** Samsung Nexus 10, LG G3
### Issue description

When setting the status of an episode to skipped, user is prompted if the want to replace the episode if has already been downloaded
### Expected result

When skipped pressed no prompt
### Steps to reproduce
1. Tap three vertical dots next to an episode of a show
2. Select set status
3. Select skipped

**Comment by MGaetan89** [comment]
On my side, I am asked what to do for every status.
From where are you trying to set the episode status? The schedule, the list of episodes in a season or the detail of an episode?

**Comment by DragonCannon** [comment]
the list of episodes in a season

**Comment by MGaetan89** [comment]
I just noticed that I misunderstood your request.
Why do you want to remove the confirmation when choosing "Skipped"?

**Comment by MGaetan89** [comment]
I'm closing this as I don't have any information on the request.
Don't hesitate to comment or create a new issue if needed.
