### ISSUE TITLE
Connection fails with basic auth and https

### ISSUE THREAD

**Issue by viperidae** [MGaetan89/ShowsRage#9]
I have SickRage set up behind a reverse proxy that does the HTTPS and basic auth.

No matter what I try, I always get a "Connection to .... failed" message when testing the connection. I have HTTPS option tick, as well as Self Signed Certificate.

I have assumed the username and password under the Api Key setting are for basic auth.

A little more information on the error message would be helping in troubleshooting these kinds of problems.

**Comment by MGaetan89** [comment]
The username/password section is only used to get the API key.
I didn't know (or think) that some SickRage configuration requires a Basic Auth to access the API. I will check that and include it in a future release.

**Comment by MGaetan89** [comment]
I am working on this feature for the next release. However, I have nothing set up to test this.
When it's ready, I will upload it as a beta version on the Play Store. Would you then to test it and tell me if it works?

**Comment by viperidae** [comment]
Is be happy to test it, just let me know when it's available

**Comment by MGaetan89** [comment]
Thanks.  I will give you news soon about this.

**Comment by MGaetan89** [comment]
I just uploaded the next version to the beta channel on the Play Store. You can access this release after you subscribed to the beta program from the following link: https://play.google.com/apps/testing/com.mgaetan89.showsrage
After that, you will receive the new update as any other application update. Let me know if the Basic Authentication feature (or anything else) works as expected for you.
If you don't want to stay in the beta program, you can leave it at anytime from the link I gave above.

**Comment by viperidae** [comment]
Basic auth works fine

Although not a problem for me, the username/password for basic auth needs to be the same as the sickrage username/password to get the API key. Perhaps add new fields for the different credentials

Another feature suggestion would be to provide some kind of feedback to the user when data is being loaded.

**Comment by MGaetan89** [comment]
Thanks for the feedback.
SickRage's username and password are only use to get the API get, and nothing else. The goal of the API key is to prevent sending the username and password with each request. So once the API key is configured, those credentials are no longer used and can safely be used for Basic Authentication, if enabled. I will add an help message to explain this in the application.

I will add a loading feedback in a future version (hopefully the next one), and also handle error message in a better way.

**Comment by MGaetan89** [comment]
It seems that images (show banner/poster/fan art) do not load when using Basic Authentication. Do you have this issue too?

**Comment by viperidae** [comment]
Yea I do. I haven't seen it with banner images so I didn't notice they were missing

**Comment by TimDowker** [comment]
Not sure if this is related but when I enable ssl I have to enable the self signed certificate option for it to work even though the certificate is valid and not self signed.

**Comment by MGaetan89** [comment]
Android checks the certificate itself, so I need to investigate to see if I can do something about this.
Except from the fact that the behavior is not straightforward, the application is working properly?
